name = "Kotlin"
grammar = "kotlin"
path_suffixes = ["kt"]
line_comments = ["// "]
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "{", end = "}", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
